spring.application.name=demo

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/BatchDB?currentSchema=batch_schema
spring.datasource.username=batch_user
spring.datasource.password=batchuser
spring.datasource.driver-class-name=org.postgresql.Driver

spring.batch.jdbc.initialize-schema=always

spring.batch.job.enabled=false